/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_spark_ml_optim_NativeCuAcc */

#ifndef _Included_org_apache_spark_ml_optim_NativeCuAcc
#define _Included_org_apache_spark_ml_optim_NativeCuAcc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_spark_ml_optim_NativeCuAcc
 * Method:    create_updater
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_spark_ml_optim_NativeCuAcc_create_1updater
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     org_apache_spark_ml_optim_NativeCuAcc
 * Method:    destroy_updater
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_apache_spark_ml_optim_NativeCuAcc_destroy_1updater
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_apache_spark_ml_optim_NativeCuAcc
 * Method:    updater_initialize
 * Signature: (J[DDI)D
 */
JNIEXPORT jdouble JNICALL Java_org_apache_spark_ml_optim_NativeCuAcc_updater_1initialize
  (JNIEnv *, jobject, jlong, jdoubleArray, jdouble, jint);

/*
 * Class:     org_apache_spark_ml_optim_NativeCuAcc
 * Method:    updater_convergence_compute
 * Signature: (J[D[DJDID[DI)D
 */
JNIEXPORT jdouble JNICALL Java_org_apache_spark_ml_optim_NativeCuAcc_updater_1convergence_1compute
  (JNIEnv *, jobject, jlong, jdoubleArray, jdoubleArray, jlong, jdouble, jint, jdouble, jdoubleArray, jint);

/*
 * Class:     org_apache_spark_ml_optim_NativeCuAcc
 * Method:    get_exec_id
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_apache_spark_ml_optim_NativeCuAcc_get_1exec_1id
  (JNIEnv *, jobject);

/*
 * Class:     org_apache_spark_ml_optim_NativeCuAcc
 * Method:    create_acc_cluster
 * Signature: (Ljava/lang/String;[D[DI)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_spark_ml_optim_NativeCuAcc_create_1acc_1cluster
  (JNIEnv *, jobject, jstring, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     org_apache_spark_ml_optim_NativeCuAcc
 * Method:    create_sparse_acc_cluster
 * Signature: (Ljava/lang/String;[D[D[I[IIZI)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_spark_ml_optim_NativeCuAcc_create_1sparse_1acc_1cluster
  (JNIEnv *, jobject, jstring, jdoubleArray, jdoubleArray, jintArray, jintArray, jint, jboolean, jint);

/*
 * Class:     org_apache_spark_ml_optim_NativeCuAcc
 * Method:    reset_acc_cluster
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_apache_spark_ml_optim_NativeCuAcc_reset_1acc_1cluster
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_apache_spark_ml_optim_NativeCuAcc
 * Method:    destroy_acc_cluster
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_apache_spark_ml_optim_NativeCuAcc_destroy_1acc_1cluster
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_apache_spark_ml_optim_NativeCuAcc
 * Method:    acc_cluster_summarize
 * Signature: (JD[D[D[D)I
 */
JNIEXPORT jint JNICALL Java_org_apache_spark_ml_optim_NativeCuAcc_acc_1cluster_1summarize
  (JNIEnv *, jobject, jlong, jdouble, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     org_apache_spark_ml_optim_NativeCuAcc
 * Method:    acc_cluster_weighten
 * Signature: (J[D[D)I
 */
JNIEXPORT jint JNICALL Java_org_apache_spark_ml_optim_NativeCuAcc_acc_1cluster_1weighten
  (JNIEnv *, jobject, jlong, jdoubleArray, jdoubleArray);

/*
 * Class:     org_apache_spark_ml_optim_NativeCuAcc
 * Method:    acc_cluster_standardize
 * Signature: (J[D[DDD)I
 */
JNIEXPORT jint JNICALL Java_org_apache_spark_ml_optim_NativeCuAcc_acc_1cluster_1standardize
  (JNIEnv *, jobject, jlong, jdoubleArray, jdoubleArray, jdouble, jdouble);

/*
 * Class:     org_apache_spark_ml_optim_NativeCuAcc
 * Method:    acc_cluster_evaluate
 * Signature: (JDD[D[D[DI)I
 */
JNIEXPORT jint JNICALL Java_org_apache_spark_ml_optim_NativeCuAcc_acc_1cluster_1evaluate
  (JNIEnv *, jobject, jlong, jdouble, jdouble, jdoubleArray, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     org_apache_spark_ml_optim_NativeCuAcc
 * Method:    acc_cluster_aug
 * Signature: (J[DD[D)V
 */
JNIEXPORT void JNICALL Java_org_apache_spark_ml_optim_NativeCuAcc_acc_1cluster_1aug
  (JNIEnv *, jobject, jlong, jdoubleArray, jdouble, jdoubleArray);

/*
 * Class:     org_apache_spark_ml_optim_NativeCuAcc
 * Method:    acc_cluster_rmse
 * Signature: (J[DD[D)V
 */
JNIEXPORT void JNICALL Java_org_apache_spark_ml_optim_NativeCuAcc_acc_1cluster_1rmse
  (JNIEnv *, jobject, jlong, jdoubleArray, jdouble, jdoubleArray);

/*
 * Class:     org_apache_spark_ml_optim_NativeCuAcc
 * Method:    compress
 * Signature: ([D[IDI)[I
 */
JNIEXPORT jintArray JNICALL Java_org_apache_spark_ml_optim_NativeCuAcc_compress
  (JNIEnv *, jobject, jdoubleArray, jintArray, jdouble, jint);

/*
 * Class:     org_apache_spark_ml_optim_NativeCuAcc
 * Method:    decompress
 * Signature: ([D[IDI)V
 */
JNIEXPORT void JNICALL Java_org_apache_spark_ml_optim_NativeCuAcc_decompress
  (JNIEnv *, jobject, jdoubleArray, jintArray, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
