/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_spark_mllib_optimization_NativeLBFGS */

#ifndef _Included_org_apache_spark_mllib_optimization_NativeLBFGS
#define _Included_org_apache_spark_mllib_optimization_NativeLBFGS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_spark_mllib_optimization_NativeLBFGS
 * Method:    runNativeLBFGS
 * Signature: ([[DDD[D[DII)V
 */
JNIEXPORT void JNICALL Java_org_apache_spark_mllib_optimization_NativeLBFGS_runNativeLBFGS
  (JNIEnv *, jobject, jobjectArray, jdouble, jdouble, jdoubleArray, jdoubleArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
