/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_spark_ml_recommendation_CuMFJNIInterface */

#ifndef _Included_org_apache_spark_ml_recommendation_CuMFJNIInterface
#define _Included_org_apache_spark_ml_recommendation_CuMFJNIInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_spark_ml_recommendation_CuMFJNIInterface
 * Method:    doALSWithCSR
 * Signature: (IIIID[[[F[I[I[F)[[F
 */
JNIEXPORT jobjectArray JNICALL Java_org_apache_spark_ml_recommendation_CuMFJNIInterface_doALSWithCSR
  (JNIEnv *, jobject, jint, jint, jint, jint, jdouble, jobjectArray, jintArray, jintArray, jfloatArray);

/*
 * Class:     org_apache_spark_ml_recommendation_CuMFJNIInterface
 * Method:    testjni
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_apache_spark_ml_recommendation_CuMFJNIInterface_testjni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
