/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_spark_mllib_classification_LogisticRegressionNative */

#ifndef _Included_org_apache_spark_mllib_classification_LogisticRegressionNative
#define _Included_org_apache_spark_mllib_classification_LogisticRegressionNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_spark_mllib_classification_LogisticRegressionNative
 * Method:    predictPoint
 * Signature: ([D[DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_apache_spark_mllib_classification_LogisticRegressionNative_predictPoint
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdouble);

#ifdef __cplusplus
}
#endif
#endif
